name = "dcc-web"
main = "worker/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[assets]
directory = "dist/client"
not_found_handling = "none"
binding = "ASSETS"

# [[routes]]
# pattern = "dcc.app/*"
# zone_name = "dcc.app"

[vars]
NEXT_PUBLIC_API_URL = "http://144.225.147.11:8000"
NEXT_PUBLIC_WS_URL  = "ws://144.225.147.11:8000/ws"
