ALTER TABLE users
ADD COLUMN IF NOT EXISTS voice_input_profile TEXT NOT NULL DEFAULT 'natural',
ADD COLUMN IF NOT EXISTS voice_input_tone SMALLINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS voice_input_effect_mix SMALLINT NOT NULL DEFAULT 60;
